openapi: 3.0.4

info:
  title: Cookie Parameters
  version: 1.0.0

paths:
  /ping:
    get:
      summary: Server ping.
      parameters:
        - name: debug
          in: cookie
          schema:
            type: integer
            enum: [0, 1]
            default: 1
        - name: csrftoken
          in: cookie
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Ping
