openapi: 3.0.4

info:
  title: Describing Parameters
  version: 1.0.0

paths:
  /users/{id}:
    get:
      summary: Get user details.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        fullName:
          type: string
      required:
        - id
        - username
