openapi: 3.0.4

info:
  title: Media Types Introduction
  version: 1.0.0

paths:
  /employees:
    get:
      summary: Get a list of employees.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  fullTime:
                    type: boolean
                example:
                  id: Employee-001
                  name: Yosep Ryan Agusta
                  fullTime: true
