openapi: 3.0.4

info:
  title: Multiple Media Types
  version: 1.0.0

paths:
  /employees:
    get:
      summary: Get a list of employees.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: Employee-001
                  name:
                    type: string
                    example: Yosep Ryan Agusta
                  fullTime:
                    type: boolean
                    example: true
            application/xml:
              schema:
                type: object
                xml:
                  name: rootElement
                  attribute: false
                  wrapped: false
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  fullTime:
                    type: boolean
